name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install MPI development packages
      run: |
        sudo apt update
        sudo apt install -y libmpich-dev  # Use this for MPICH

    - name: Install BLAS and LAPACK libraries
      run: |
        sudo apt install -y libblas-dev liblapack-dev

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest
