name: Run Tests & Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          # Install platform-specific dependencies
          if [[ $RUNNER_OS == 'Linux' ]]; then
            sudo apt-get update
            sudo apt-get install -y libblas-dev liblapack-dev
          fi
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8

      - name: Run Linter
        run: |
          flake8 src/

      - name: Run Tests with Coverage
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml