name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libmpich-dev libblas-dev liblapack-dev libopenmpi-dev
        sudo apt install -y software-properties-common
        sudo add-apt-repository ppa:petsc/petsc-dev
        sudo apt update
        sudo apt install -y libpetsc-dev

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython  # Ensure Cython is installed before anything else

    - name: Create virtual environment and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install pytest  # Ensure pytest is installed

    - name: Set environment variables
      run: |
        echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
        echo "PETSC_DIR=/usr/lib/petsc" >> $GITHUB_ENV  # Set PETSc location

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests/
