name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libmpich-dev libblas-dev liblapack-dev libopenmpi-dev

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython petsc4py  # Install PETSc bindings for Python
        pip install pytest  # Ensure pytest is installed
        pip install PyYAML
        pip install scipy
        pip install h5py  # Install h5py to handle HDF5 files

    - name: Create virtual environment and install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "PYTHONPATH=src" >> $GITHUB_ENV
        echo "PETSC_DIR=/usr/lib/petsc" >> $GITHUB_ENV  # Set PETSc location

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests/
