name: Create Release

on:
  push:
    tags:
      - 'v*'  # Matches tags like v1.0.0, v1.2.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        uses: softprops/action-gh-release@v2  # Use the latest version
        with:
          files: |
            results/simulation_results.h5
            results/fit_results.h5